# render.yaml
# =========================================================
# PLANMA Backend - Render Deployment
# =========================================================

services:
  # -------------------------------------------------------
  # 1️⃣ Web Service - Django + Daphne (ASGI)
  # -------------------------------------------------------
  - type: web
    name: planma-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT planmaDB.asgi:application
    autoDeploy: true
    envVars:
      # Database (Supabase)
      - key: DATABASE_URL
        sync: false
      # Redis (Render Redis add-on)
      - key: REDIS_URL
        sync: false
      # Django settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: planmaDB.settings
      # Optional Firebase JSON if using env-based approach
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      # Needed for Render HTTPS handling
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: planma-backend
          property: host

  # -------------------------------------------------------
  # 2️⃣ Celery Worker - handles async tasks
  # -------------------------------------------------------
  - type: worker
    name: planma-celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A planmaDB worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: planmaDB.settings
      - key: SECRET_KEY
        sync: false

  # -------------------------------------------------------
  # 3️⃣ Celery Beat - scheduler for periodic tasks
  # -------------------------------------------------------
  - type: worker
    name: planma-celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A planmaDB beat --loglevel=info
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: planmaDB.settings
      - key: SECRET_KEY
        sync: false
