# Generated by Django 5.1.3 on 2024-11-16 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customtask_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_desc', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('act_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('date_logged', models.DateField()),
                ('activity_id', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='actlog', to='api.customactivity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.TextField()),
                ('location', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendedEvents',
            fields=[
                ('att_events_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('has_attended', models.BooleanField()),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='att_Ev', to='api.customevents')),
            ],
        ),
    ]
