# Generated by Django 5.1.3 on 2024-11-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customactivity_activitylog_customevents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendedevents',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='customactivity',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='customevents',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='AttendedEvents',
        ),
        migrations.DeleteModel(
            name='CustomActivity',
        ),
        migrations.DeleteModel(
            name='CustomEvents',
        ),
    ]
