# Generated by Django 5.1.3 on 2024-11-17 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customactivity_activitylog_customevents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomClass',
            fields=[
                ('classsched_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=10)),
                ('day_of_week', models.IntegerField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('room', models.CharField(max_length=75)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendedClass',
            fields=[
                ('att_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hasAttended', models.BooleanField()),
                ('classched_id', models.ForeignKey(db_column='classsched_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendedclass', to='api.customclass')),
            ],
        ),
        migrations.CreateModel(
            name='ExcusedClass',
            fields=[
                ('exc_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isExcused', models.BooleanField()),
                ('classched_id', models.ForeignKey(db_column='classsched_id', on_delete=django.db.models.deletion.CASCADE, related_name='excusedclass', to='api.customclass')),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('pref_id', models.AutoField(primary_key=True, serialize=False)),
                ('usual_sleep_time', models.TimeField()),
                ('usual_wake_time', models.TimeField()),
                ('notification_enabled', models.BooleanField()),
                ('reminder_offset_time', models.TimeField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='userpref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
