# Generated by Django 5.1.3 on 2024-11-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customclass_attendedclass_excusedclass_userpref'),
        ('api', '0007_remove_attendedevents_event_id_and_more'),
    ]

    operations = [
    ]
