# Generated by Django 5.1.3 on 2024-11-18 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customactivity_activitylog_customevents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedclass',
            name='isExcused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customclass',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomSub',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_title', models.TextField()),
                ('semester_id', models.TextField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customclass',
            name='subject_code',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.customsub'),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=100)),
                ('target_hours', models.TimeField()),
                ('timeframe', models.TimeField()),
                ('goal_desc', models.TextField()),
                ('goal_type', models.CharField(max_length=30)),
                ('semester_id', models.TextField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('goalprogress_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('session_duration', models.TimeField()),
                ('goal_id', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='goalprog', to='api.goals')),
            ],
        ),
        migrations.CreateModel(
            name='GoalSchedule',
            fields=[
                ('goalschedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('goal_id', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='goalsched', to='api.goals')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_id', models.TextField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExcusedClass',
        ),
    ]
