# Generated by Django 5.1.3 on 2024-11-19 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attendedclass_isexcused_alter_customclass_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='count_activities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_subjects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='reportstud', to=settings.AUTH_USER_MODEL),
        ),
    ]
