# Generated by Django 5.1.3 on 2024-11-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_report_count_activities_report_count_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSemester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('acad_year_start', models.IntegerField()),
                ('acad_year_end', models.IntegerField()),
                ('year_level', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('sem_start_date', models.DateField()),
                ('sem_end_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='count_activities',
            new_name='count_activities_total',
        ),
        migrations.RemoveField(
            model_name='report',
            name='count_events',
        ),
        migrations.RemoveField(
            model_name='report',
            name='count_subjects',
        ),
        migrations.RemoveField(
            model_name='report',
            name='count_tasks',
        ),
        migrations.AddField(
            model_name='report',
            name='count_activities_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_activities_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_class_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_class_excused',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_class_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_events_academictype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_events_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_events_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_events_personaltype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_events_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_tasks_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_tasks_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='count_tasks_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customsub',
            name='semester_id',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='subsems', to='api.customsemester'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='semester_id',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='goalsems', to='api.customsemester'),
        ),
        migrations.AlterField(
            model_name='report',
            name='semester_id',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='repsems', to='api.customsemester'),
        ),
    ]
