# Generated by Django 5.1.3 on 2024-11-21 01:20

import api.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customsemester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customactivity',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=api.models.EnumFields),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=api.models.EnumFields),
        ),
    ]
