# Generated by Django 5.1.3 on 2024-11-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customsemester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customactivity',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], max_length=50),
        ),
    ]
