# Generated by Django 5.1.3 on 2024-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customsemester_acad_year_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsemester',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=12),
        ),
        migrations.AlterField(
            model_name='customsemester',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], max_length=9),
        ),
    ]
