# Generated by Django 5.1.3 on 2024-11-26 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_customclass_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclassschedule',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('sleep_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('date_logged', models.DateField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
