# Generated by Django 5.1.3 on 2024-11-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customclassschedule_day_of_week_sleeplog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customactivity',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
