# Generated by Django 5.1.3 on 2024-12-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customactivity_status_alter_customtask_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customclassschedule',
            unique_together={('day_of_week', 'scheduled_start_time', 'scheduled_end_time', 'room', 'student_id')},
        ),
    ]
