# Generated by Django 5.1.3 on 2024-12-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customclassschedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='subject_code',
            field=models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='api.customsubject'),
        ),
    ]
