# Generated by Django 5.1.3 on 2024-12-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customtask_status_and_more'),
        ('api', '0020_remove_userpref_notification_enabled_and_more'),
    ]

    operations = [
    ]
