# Generated by Django 5.1.3 on 2024-12-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customtask_status_and_more'),
    ]

    operations = [
        
    ]
