# Generated by Django 5.1.3 on 2024-12-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20241209_2043'),
        ('api', '0024_merge_20241209_2147'),
    ]

    operations = [
    ]
