# Generated by Django 5.1.3 on 2024-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20241209_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpref',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterField(
            model_name='userpref',
            name='usual_sleep_time',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='usual_wake_time',
            field=models.TimeField(default='07:00'),
        ),
    ]
