# Generated by Django 5.1.3 on 2024-12-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userpref_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='reminder_offset_time',
            field=models.DurationField(),
        ),
    ]
