# Generated by Django 5.1.3 on 2024-12-15 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_userpref_reminder_offset_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsemester',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', default='ae88ee45-d933-4149-9a20-54f91b55109e', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
