# Generated by Django 5.1.3 on 2024-12-18 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customsemester_student_id'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='customclassschedule',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', default=100, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.customsubject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customclassschedule',
            unique_together={('subject', 'day_of_week', 'scheduled_start_time', 'scheduled_end_time', 'room', 'student_id')},
        ),
    ]
