# Generated by Django 5.1.3 on 2024-12-18 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_customclassschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', default=100, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='api.customsubject'),
            preserve_default=False,
        ),
    ]
