# Generated by Django 5.1.3 on 2025-01-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_customclassschedule_attendedclass_customsubject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendedclass',
            old_name='classched_id',
            new_name='classsched_id',
        ),
        migrations.RenameField(
            model_name='goalprogress',
            old_name='scheduled_end_time',
            new_name='session_end_time',
        ),
        migrations.RenameField(
            model_name='goalprogress',
            old_name='scheduled_start_time',
            new_name='session_start_time',
        ),
        migrations.RemoveField(
            model_name='attendedclass',
            name='hasAttended',
        ),
        migrations.RemoveField(
            model_name='attendedclass',
            name='isExcused',
        ),
        migrations.AddField(
            model_name='attendedclass',
            name='status',
            field=models.CharField(choices=[('Did Not Attend', 'Did Not Attend'), ('Excused', 'Excused'), ('Attended', 'Attended')], default='Did Not Attend', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='session_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='session_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.CreateModel(
            name='ActivityTimeLog',
            fields=[
                ('activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('date_logged', models.DateField()),
                ('activity_id', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='actlog', to='api.customactivity')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTimeLog',
            fields=[
                ('task_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('date_logged', models.DateField()),
                ('task_id', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasklog', to='api.customtask')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
