# Generated by Django 5.1.3 on 2025-01-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_goalprogress_goalschedule_id_goalschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalprogress',
            name='goalschedule_id',
            field=models.ForeignKey(db_column='goalschedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='progresslogs', to='api.goalschedule'),
        ),
    ]
