# Generated by Django 5.1.3 on 2025-02-14 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_attendedclass_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('Task', 'Task'), ('Class', 'Class'), ('Event', 'Event'), ('Activity', 'Activity'), ('Goal', 'Goal')], max_length=50)),
                ('reference_id', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_id', 'scheduled_date', 'scheduled_start_time', 'scheduled_end_time', 'category_type', 'reference_id')},
            },
        ),
    ]
