# Generated by Django 5.1.8 on 2025-04-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_customclassschedule_last_reminder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
