# Generated by Django 5.1.8 on 2025-04-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_customtask_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customactivity',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customevents',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpref',
            name='last_sleep_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
