# Generated by Django 5.1.3 on 2025-11-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customtask',
            index=models.Index(fields=['student_id'], name='api_customt_student_bb34ed_idx'),
        ),
        migrations.AddIndex(
            model_name='customtask',
            index=models.Index(fields=['scheduled_date'], name='api_customt_schedul_d49474_idx'),
        ),
        migrations.AddIndex(
            model_name='customtask',
            index=models.Index(fields=['status'], name='api_customt_status_72b4b8_idx'),
        ),
    ]
