# Generated by Django 5.1.3 on 2025-11-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_customtask_api_customt_student_bb34ed_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customtask',
            name='api_customt_student_bb34ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='customtask',
            name='api_customt_schedul_d49474_idx',
        ),
        migrations.RemoveIndex(
            model_name='customtask',
            name='api_customt_status_72b4b8_idx',
        ),
    ]
